application: biiunicorn
version: 1
api_version: 1
runtime: python27
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: .*
  script: hello.py
